# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under sunny_mlops/resources/*
# and sunny_mlops/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: test github actions sunny DABS

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./files

env:
  DATABRICKS_CLIENT_ID_STAGING: "56ab6d40-3e23-4041-bc36-f74cd0c0d926"
  DATABRICKS_CLIENT_SECRET_STAGING: "dosec6bb027fa5932fd492b6a7d103c3d39d"
  DATABRICKS_HOST_STAGING: "https://adb-984752964297111.11.azuredatabricks.net"
  DATABRICKS_CLIENT_ID_PROD: "56ab6d40-3e23-4041-bc36-f74cd0c0d926"
  DATABRICKS_CLIENT_SECRET_PROD: "dosec6bb027fa5932fd492b6a7d103c3d39d"
  DATABRICKS_HOST_PROD: "https://adb-984752964297111.11.azuredatabricks.net"

jobs:
  dev:
    # concurrency: sunny_DABS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.258.0
      - name: Validate Bundle For dev
        id: validate_bundle
        env:
          DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID_STAGING)
          DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET_STAGING)
          DATABRICKS_HOST: $(DATABRICKS_HOST_STAGING)
  
        run: |
          databricks bundle validate -t dev
      - name: Deploy Bundle to dev
        id: deploy_bundle
        env:
          DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID_STAGING)
          DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET_STAGING)
          DATABRICKS_HOST: $(DATABRICKS_HOST_STAGING)
        run: |
          databricks bundle deploy -t dev
      - name: Run Bundle on dev
        id: run_bundle
        env:
          DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID_STAGING)
          DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET_STAGING)
          DATABRICKS_HOST: $(DATABRICKS_HOST_STAGING)
        run: |
          databricks bundle run -t dev
  prod:
    needs: dev
    # concurrency: sunny_DABS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.258.0
      - name: Validate Bundle For prod
        id: validate_bundle
        env:
          DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID_PROD)
          DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET_PROD)
          DATABRICKS_HOST: $(DATABRICKS_HOST_PROD)
  
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to prod
        id: deploy_bundle
        env:
          DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID_PROD)
          DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET_PROD)
          DATABRICKS_HOST: $(DATABRICKS_HOST_PROD)
        run: |
          databricks bundle deploy -t prod
      - name: Run Bundle on prod
        id: run_bundle
        env:
          DATABRICKS_CLIENT_ID: $(DATABRICKS_CLIENT_ID_PROD)
          DATABRICKS_CLIENT_SECRET: $(DATABRICKS_CLIENT_SECRET_PROD)
          DATABRICKS_HOST: $(DATABRICKS_HOST_PROD)
        run: |
          databricks bundle run -t prod


